-- 버스 지하철 추가
ALTER TABLE TB_EXHIBITION_INFO
ADD bus VARCHAR(100);

ALTER TABLE TB_EXHIBITION_INFO
ADD subway VARCHAR(100);

SELECT * FROM TB_EXHIBITION_INFO;

DELETE FROM TB_EXHIBITION_INFO WHERE round != 1;

DELETE FROM TB_FILES WHERE round = 2;

SELECT * FROM TB_FILES;

SELECT COUNT(*)
FROM TB_POSTING
WHERE company_id = 1 AND (status = '마감' OR round < 1);

SELECT * FROM TB_POSTING
WHERE company_id = 1 AND (status = '마감' OR round < 2);